version: '3.8'

services:
  
  nginx:
    image: nginx
    container_name: nano_nginx_container
    restart: always
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - shared-network
    depends_on:
      - server
      - client

  server:
    container_name: aiqsarnano_server
    restart: unless-stopped
    image: aiqsarnano-server-image:1.0.0
    build:
      context: backend 
      dockerfile: Dockerfile
    ports:  #outside:inside(container)
      - 8000:8000
    networks:
      - shared-network

  client:
    container_name: aiqsarnano_client
    restart: unless-stopped
    image: aiqsarnano-client-image:1.0.0
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:  #outside:inside(container)
      - 3000:3000
    # volumes:
    #   - ./certs/devopsbyexample-key.pem:/etc/nginx/certs/devopsbyexample-key.pem
    #   - ./certs/devopsbyexample.pem:/etc/nginx/certs/devopsbyexample.pem
    networks:
      - shared-network
    depends_on:
      - server

networks:
  shared-network: